WebApp/Models/SpecialityViewModel.cs
namespace WebApp.Models
{
    public class SpecialityViewModel
    {
        public int Id { get; set; }
        public string NameOfSpeciality { get; set; }
        public string Department { get; set; }
    }
}

WebApp/Controllers/SpecialitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BLL.Interfaces;
using Entities.DTOModels;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class SpecialitiesController: Controller
    {
        private readonly IManager<SpecialityDTO>_specialityManager;
        private readonly IManager<DepartmentDTO>_departmentManager;

        public SpecialitiesController(IManager<SpecialityDTO> specialityManager, IManager<DepartmentDTO> departmentManager)
        {
            _specialityManager = specialityManager;
            _departmentManager = departmentManager;
        }
        public ActionResult Index(string searchString)
        {
            var specialities = new List<SpecialityViewModel>();
            if (String.IsNullOrEmpty(searchString))
            {
                foreach (var speciality in _specialityManager.GetAll())
                {
                    var department = _departmentManager.GetById(speciality.DepartmentId).NameOfDepartment;
                    var specialityViewModel = new SpecialityViewModel
                    {
                        Id = speciality.Id,
                        NameOfSpeciality = speciality.NameOfSpeciality,
                        Department = department
                    };
                    specialities.Add(specialityViewModel);
                }
            }
            else
            {
                var departmentId = _departmentManager.GetAll().Where(t => t.NameOfDepartment.Equals(searchString)).ToList()
                    .First().Id;
                foreach (var speciality in _specialityManager.GetAll().Where(t => t.DepartmentId.Equals(departmentId)).ToList())
                {
                    var specialityViewModel = new SpecialityViewModel
                    {
                        Id = speciality.Id,
                        NameOfSpeciality = speciality.NameOfSpeciality,
                        Department = _departmentManager.GetById(departmentId).NameOfDepartment
                    };
                    specialities.Add(specialityViewModel);
                }
            }

            return View(specialities);
        }
        
        public ActionResult Create()
        {
            ViewBag.Departments = _departmentManager.GetAll();
            return View();
        }

        [HttpPost]
        public ActionResult Create(SpecialityViewModel specialityViewModel)
        {
            if (ModelState.IsValid)
            {
                var speciality = new SpecialityDTO
                {
                    NameOfSpeciality = specialityViewModel.NameOfSpeciality,
                    DepartmentId = _departmentManager.GetAll().Where(t => t.NameOfDepartment.Equals(specialityViewModel.Department)).ToList().First().Id
                };
                _specialityManager.Create(speciality);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        
        public ActionResult Edit(int id)
        {
            var speciality = _specialityManager.GetById(id);
            var specialityViewModel = new SpecialityViewModel
            {
                Id = speciality.Id,
                NameOfSpeciality = speciality.NameOfSpeciality,
                Department = _departmentManager.GetById(speciality.DepartmentId).NameOfDepartment
            };
            ViewBag.Departments = _departmentManager.GetAll();
            return View(specialityViewModel);
        }
        
        [HttpPost]
        public ActionResult Edit(int id, SpecialityViewModel specialityViewModel)
        {
            if (ModelState.IsValid)
            {
                var departmentId = _departmentManager.GetAll().Where(t => t.NameOfDepartment.Equals(specialityViewModel.Department)).ToList()
                    .First().Id;
                var speciality = new SpecialityDTO
                {
                    Id = specialityViewModel.Id,
                    NameOfSpeciality = specialityViewModel.NameOfSpeciality,
                    DepartmentId = departmentId
                };
                _specialityManager.Update(speciality);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        
        [HttpGet]
        public ActionResult Delete(int id)
        { 
            var speciality = _specialityManager.GetById(id);
            return View(speciality);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                _specialityManager.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
 
    }
}

WebApp/Views/Specialities/Create.cshtml
@using Entities.DTOModels
@model WebApp.Models.SpecialityViewModel

@{
    ViewData["Title"] = "Create";
    var departments = new List<SelectListItem>();

    foreach (DepartmentDTO p in ViewBag.Departments)
    {
        departments.Add(new SelectListItem { Text = p.NameOfDepartment, Value = p.NameOfDepartment });
    }
}

<h1>Create</h1>

<h4>Speciality</h4>

<div class="modal-content">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="NameOfSpeciality" class="control-label"></label>
                        <input asp-for="NameOfSpeciality" class="form-control" />
                        <span asp-validation-for="NameOfSpeciality" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Department" class="control-label"></label>
                        <select asp-for="Department" class="form-control" 
                                asp-items="@(new SelectList(departments, "Value", "Text"))">
                        </select>
                        <span asp-validation-for="Department" class="text-danger"></span>
                    </div>
            
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
         <a asp-action="Index">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Specialities/Delete.cshtml
@model Entities.DTOModels.SpecialityDTO

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<div>
    <h4>Speciality</h4>
    
    <div class="modal-content">
        <div class="modal-body">
            <dl class="row">
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.NameOfSpeciality)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.NameOfSpeciality)
                </dd>
            </dl>
    
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Delete" class="btn btn-danger" /> 
            </form>
        </div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

WebApp/Views/Specialities/Edit.cshtml
@using Entities.DTOModels
@model WebApp.Models.SpecialityViewModel

@{
    ViewData["Title"] = "Edit";
    var departments = new List<SelectListItem>();

    foreach (DepartmentDTO p in ViewBag.Departments)
    {
        departments.Add(new SelectListItem { Text = p.NameOfDepartment, Value = p.NameOfDepartment });
    }
}

<h1>Edit</h1>

<h4>Speciality</h4>

<div class="modal-content">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="NameOfSpeciality" class="control-label"></label>
                        <input asp-for="NameOfSpeciality" class="form-control" />
                        <span asp-validation-for="NameOfSpeciality" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Department" class="control-label"></label>
                        <select asp-for="Department" class="form-control"
                                asp-items="@(new SelectList(departments, "Value", "Text"))"></select>
                        <span asp-validation-for="Department" class="text-danger"></span>
                    </div>
            
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary"/>
                    </div>
                </form>
            </div>
        </div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Specialities/Index.cshtml
@model IEnumerable<WebApp.Models.SpecialityViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Speciality</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Specialities" asp-action="Index" method="get">
    <p>
        NameOfDepartment: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NameOfSpeciality)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NameOfSpeciality)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>